sudo: false
language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - 14
before_install:
  - npm i -g npm
before_script:
  - npm prune
script:
  - npm run test
install: npm i --ignore-scripts
